"""add_sales_model

Revision ID: 0c4bad721113
Revises: b861ad02334f
Create Date: 2026-06-09 11:27:49.627424
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c4bad721113'
down_revision = 'b861ad02334f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('discount_percent', sa.Integer(), nullable=False),
    sa.Column('applies_to', sa.String(length=50), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('announcement', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('active_sales')
    # ### end Alembic commands ###

