"""baseline

Revision ID: 52dbdc79dabb
Revises: 
Create Date: 2026-06-09 08:30:22.776210
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52dbdc79dabb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lottery_rounds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('week_key', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ticket_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('numbers_pool', sa.Integer(), nullable=False),
    sa.Column('numbers_per_ticket', sa.Integer(), nullable=False),
    sa.Column('drawn_numbers', sa.Text(), nullable=True),
    sa.Column('prize_pool', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('draw_starts_at', sa.DateTime(), nullable=False),
    sa.Column('draw_ends_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lottery_rounds_week_key'), 'lottery_rounds', ['week_key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=32), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('agreed_to_rules', sa.Boolean(), nullable=False),
    sa.Column('nickname_set', sa.Boolean(), nullable=False),
    sa.Column('referral_code', sa.String(length=50), nullable=True),
    sa.Column('referred_by_user_id', sa.Integer(), nullable=True),
    sa.Column('referral_earnings', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('referrals_count', sa.Integer(), nullable=False),
    sa.Column('referral_milestone_level', sa.Integer(), nullable=False),
    sa.Column('last_bonus_at', sa.DateTime(), nullable=True),
    sa.Column('bonus_streak', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('vip_until', sa.DateTime(), nullable=True),
    sa.Column('promo_created_this_month', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['referred_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referral_code')
    )
    op.create_index(op.f('ix_users_display_name'), 'users', ['display_name'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('balance_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance_before', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balance_logs_created_at'), 'balance_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_balance_logs_user_id'), 'balance_logs', ['user_id'], unique=False)
    op.create_table('daily_quest_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quest_type', sa.String(length=50), nullable=False),
    sa.Column('quest_date', sa.Date(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('reward', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('reward_claimed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'quest_type', 'quest_date', name='uq_user_quest_date')
    )
    op.create_table('feedback_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_messages_created_at'), 'feedback_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_feedback_messages_user_id'), 'feedback_messages', ['user_id'], unique=False)
    op.create_table('game_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_type', sa.String(length=50), nullable=False),
    sa.Column('bet', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('result', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_history_created_at'), 'game_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_game_history_user_id'), 'game_history', ['user_id'], unique=False)
    op.create_table('game_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_sessions_user_id'), 'game_sessions', ['user_id'], unique=False)
    op.create_table('lootbox_opens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payment_payload', sa.String(length=255), nullable=True),
    sa.Column('pay_currency', sa.String(length=10), nullable=False),
    sa.Column('price_coins', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_stars', sa.Integer(), nullable=False),
    sa.Column('reward_coins', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rarity', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_payload', name='uq_lootbox_payment_payload')
    )
    op.create_index(op.f('ix_lootbox_opens_created_at'), 'lootbox_opens', ['created_at'], unique=False)
    op.create_index(op.f('ix_lootbox_opens_user_id'), 'lootbox_opens', ['user_id'], unique=False)
    op.create_table('lottery_tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('numbers', sa.String(length=100), nullable=False),
    sa.Column('matched_count', sa.Integer(), nullable=False),
    sa.Column('reward_paid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['lottery_rounds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lottery_tickets_round_id'), 'lottery_tickets', ['round_id'], unique=False)
    op.create_index(op.f('ix_lottery_tickets_user_id'), 'lottery_tickets', ['user_id'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creator_user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('channel_url', sa.Text(), nullable=False),
    sa.Column('reward_preview', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reward_final', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('penalty_unsubscribe', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_rentable', sa.Boolean(), nullable=False),
    sa.Column('rent_cost_per_day', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_simultaneous_rentals', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.String(length=255), nullable=False),
    sa.Column('stars_amount', sa.Integer(), nullable=False),
    sa.Column('coins_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payload')
    )
    op.create_table('promocodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creator_user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('coin_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_via_stars', sa.Boolean(), nullable=False),
    sa.Column('stars_paid', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promocodes_code'), 'promocodes', ['code'], unique=True)
    op.create_index(op.f('ix_promocodes_creator_user_id'), 'promocodes', ['creator_user_id'], unique=False)
    op.create_table('trusted_uploaders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('trusted_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trusted_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_user_id', 'trusted_user_id', name='uq_admin_trusted_user')
    )
    op.create_index(op.f('ix_trusted_uploaders_admin_user_id'), 'trusted_uploaders', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_trusted_uploaders_created_at'), 'trusted_uploaders', ['created_at'], unique=False)
    op.create_index(op.f('ix_trusted_uploaders_trusted_user_id'), 'trusted_uploaders', ['trusted_user_id'], unique=False)
    op.create_table('user_action_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_action_logs_user_id'), 'user_action_logs', ['user_id'], unique=False)
    op.create_table('user_ad_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_offer_shown_at', sa.DateTime(), nullable=True),
    sa.Column('last_low_balance_hint_at', sa.DateTime(), nullable=True),
    sa.Column('forced_offer_id', sa.Integer(), nullable=True),
    sa.Column('forced_offer_shown_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_ad_states_user_id'), 'user_ad_states', ['user_id'], unique=True)
    op.create_table('videos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uploader_user_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('telegram_file_id', sa.Text(), nullable=False),
    sa.Column('telegram_file_unique_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploader_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_telegram_file_unique_id'), 'videos', ['telegram_file_unique_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_reactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('reaction_type', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'video_id', name='uq_user_video_reaction')
    )
    op.create_table('offer_participations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reward_given', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('unsubscribed_penalized_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'offer_id', name='uq_user_offer')
    )
    op.create_table('offer_rentals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('renter_user_id', sa.Integer(), nullable=False),
    sa.Column('renter_channel_title', sa.String(length=255), nullable=False),
    sa.Column('renter_channel_url', sa.Text(), nullable=False),
    sa.Column('rent_days', sa.Integer(), nullable=False),
    sa.Column('cost_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['renter_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offer_rentals_offer_id'), 'offer_rentals', ['offer_id'], unique=False)
    op.create_index(op.f('ix_offer_rentals_renter_user_id'), 'offer_rentals', ['renter_user_id'], unique=False)
    op.create_table('promocode_activations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('promocode_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['promocode_id'], ['promocodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('promocode_id', 'user_id', name='uq_promo_user')
    )
    op.create_index(op.f('ix_promocode_activations_promocode_id'), 'promocode_activations', ['promocode_id'], unique=False)
    op.create_table('video_ratings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'video_id', name='uq_user_video_rating')
    )
    op.create_table('video_views',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('watched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'video_id', name='uq_user_video_view')
    )
    op.create_index(op.f('ix_video_views_watched_at'), 'video_views', ['watched_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_views_watched_at'), table_name='video_views')
    op.drop_table('video_views')
    op.drop_table('video_ratings')
    op.drop_index(op.f('ix_promocode_activations_promocode_id'), table_name='promocode_activations')
    op.drop_table('promocode_activations')
    op.drop_index(op.f('ix_offer_rentals_renter_user_id'), table_name='offer_rentals')
    op.drop_index(op.f('ix_offer_rentals_offer_id'), table_name='offer_rentals')
    op.drop_table('offer_rentals')
    op.drop_table('offer_participations')
    op.drop_table('content_reactions')
    op.drop_table('comments')
    op.drop_index(op.f('ix_videos_telegram_file_unique_id'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_user_ad_states_user_id'), table_name='user_ad_states')
    op.drop_table('user_ad_states')
    op.drop_index(op.f('ix_user_action_logs_user_id'), table_name='user_action_logs')
    op.drop_table('user_action_logs')
    op.drop_index(op.f('ix_trusted_uploaders_trusted_user_id'), table_name='trusted_uploaders')
    op.drop_index(op.f('ix_trusted_uploaders_created_at'), table_name='trusted_uploaders')
    op.drop_index(op.f('ix_trusted_uploaders_admin_user_id'), table_name='trusted_uploaders')
    op.drop_table('trusted_uploaders')
    op.drop_index(op.f('ix_promocodes_creator_user_id'), table_name='promocodes')
    op.drop_index(op.f('ix_promocodes_code'), table_name='promocodes')
    op.drop_table('promocodes')
    op.drop_table('payments')
    op.drop_table('offers')
    op.drop_index(op.f('ix_lottery_tickets_user_id'), table_name='lottery_tickets')
    op.drop_index(op.f('ix_lottery_tickets_round_id'), table_name='lottery_tickets')
    op.drop_table('lottery_tickets')
    op.drop_index(op.f('ix_lootbox_opens_user_id'), table_name='lootbox_opens')
    op.drop_index(op.f('ix_lootbox_opens_created_at'), table_name='lootbox_opens')
    op.drop_table('lootbox_opens')
    op.drop_index(op.f('ix_game_sessions_user_id'), table_name='game_sessions')
    op.drop_table('game_sessions')
    op.drop_index(op.f('ix_game_history_user_id'), table_name='game_history')
    op.drop_index(op.f('ix_game_history_created_at'), table_name='game_history')
    op.drop_table('game_history')
    op.drop_index(op.f('ix_feedback_messages_user_id'), table_name='feedback_messages')
    op.drop_index(op.f('ix_feedback_messages_created_at'), table_name='feedback_messages')
    op.drop_table('feedback_messages')
    op.drop_table('daily_quest_progress')
    op.drop_index(op.f('ix_balance_logs_user_id'), table_name='balance_logs')
    op.drop_index(op.f('ix_balance_logs_created_at'), table_name='balance_logs')
    op.drop_table('balance_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_display_name'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_lottery_rounds_week_key'), table_name='lottery_rounds')
    op.drop_table('lottery_rounds')
    # ### end Alembic commands ###

